# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addmoney.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddMoneyForm(object):
    def setupUi(self, AddMoneyForm):
        AddMoneyForm.setObjectName("AddMoneyForm")
        AddMoneyForm.resize(559, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddMoneyForm.sizePolicy().hasHeightForWidth())
        AddMoneyForm.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(AddMoneyForm)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(AddMoneyForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(AddMoneyForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.widget)
        self.vboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.vboxlayout1.addWidget(self.label_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.hboxlayout.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.button50 = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.button50.setFont(font)
        self.button50.setText("")
        icon = QtGui.QIcon()
        icon.addFile(":/img/img/50kr.png")
        self.button50.setIcon(icon)
        self.button50.setIconSize(QtCore.QSize(144, 81))
        self.button50.setFlat(True)
        self.button50.setObjectName("button50")
        self.hboxlayout.addWidget(self.button50)
        self.button100 = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.button100.setFont(font)
        self.button100.setText("")
        icon1 = QtGui.QIcon()
        icon1.addFile(":/img/img/100kr.png")
        self.button100.setIcon(icon1)
        self.button100.setIconSize(QtCore.QSize(151, 85))
        self.button100.setFlat(True)
        self.button100.setObjectName("button100")
        self.hboxlayout.addWidget(self.button100)
        self.button200 = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.button200.setFont(font)
        self.button200.setText("")
        icon2 = QtGui.QIcon()
        icon2.addFile(":/img/img/200kr.png")
        self.button200.setIcon(icon2)
        self.button200.setIconSize(QtCore.QSize(156, 85))
        self.button200.setFlat(True)
        self.button200.setObjectName("button200")
        self.hboxlayout.addWidget(self.button200)
        self.vboxlayout1.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.hboxlayout1 = QtWidgets.QHBoxLayout(self.widget_3)
        self.hboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.hboxlayout1.addWidget(self.label_6)
        self.amountField = QtWidgets.QDoubleSpinBox(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.amountField.setFont(font)
        self.amountField.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.amountField.setMinimum(-1000000000.0)
        self.amountField.setMaximum(1000000000.0)
        self.amountField.setObjectName("amountField")
        self.hboxlayout1.addWidget(self.amountField)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.vboxlayout1.addWidget(self.widget_3)
        self.vboxlayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(AddMoneyForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.hboxlayout2.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.addButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.addButton.setFont(font)
        self.addButton.setAutoDefault(True)
        self.addButton.setDefault(True)
        self.addButton.setObjectName("addButton")
        self.hboxlayout2.addWidget(self.addButton)
        self.cancelButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout2.addWidget(self.cancelButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem3)
        self.vboxlayout.addWidget(self.widget_2)
        self.label_6.setBuddy(self.amountField)

        self.retranslateUi(AddMoneyForm)
        self.cancelButton.clicked.connect(AddMoneyForm.close)
        QtCore.QMetaObject.connectSlotsByName(AddMoneyForm)
        AddMoneyForm.setTabOrder(self.button50, self.button100)
        AddMoneyForm.setTabOrder(self.button100, self.button200)
        AddMoneyForm.setTabOrder(self.button200, self.addButton)
        AddMoneyForm.setTabOrder(self.addButton, self.cancelButton)

    def retranslateUi(self, AddMoneyForm):
        _translate = QtCore.QCoreApplication.translate
        AddMoneyForm.setWindowTitle(_translate("AddMoneyForm", "Indsæt penge"))
        self.label.setText(_translate("AddMoneyForm", "Indsæt penge"))
        self.label_2.setText(_translate("AddMoneyForm", "Indtast beløb eller klik på en af pengesedlerne"))
        self.label_6.setText(_translate("AddMoneyForm", "&Beløb:"))
        self.amountField.setSuffix(_translate("AddMoneyForm", " kr"))
        self.addButton.setText(_translate("AddMoneyForm", "&Indsæt"))
        self.cancelButton.setText(_translate("AddMoneyForm", "&Annuller"))

import fvk_rc
