# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adduser.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddUserForm(object):
    def setupUi(self, AddUserForm):
        AddUserForm.setObjectName("AddUserForm")
        AddUserForm.resize(316, 222)
        self.gridlayout = QtWidgets.QGridLayout(AddUserForm)
        self.gridlayout.setContentsMargins(9, 9, 9, 9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.widget_2 = QtWidgets.QWidget(AddUserForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.hboxlayout.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.createButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.createButton.setFont(font)
        self.createButton.setObjectName("createButton")
        self.hboxlayout.addWidget(self.createButton)
        self.cancelButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.gridlayout.addWidget(self.widget_2, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(AddUserForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.gridlayout1 = QtWidgets.QGridLayout(self.widget)
        self.gridlayout1.setContentsMargins(9, 9, 9, 9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.gridlayout1.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.gridlayout1.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.gridlayout1.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 1, 2, 1, 1)
        self.cardNoField = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.cardNoField.setFont(font)
        self.cardNoField.setObjectName("cardNoField")
        self.gridlayout1.addWidget(self.cardNoField, 2, 1, 1, 2)
        self.nameField = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.nameField.setFont(font)
        self.nameField.setObjectName("nameField")
        self.gridlayout1.addWidget(self.nameField, 0, 1, 1, 2)
        self.houseField = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.houseField.setFont(font)
        self.houseField.setObjectName("houseField")
        self.gridlayout1.addWidget(self.houseField, 1, 1, 1, 1)
        self.gridlayout.addWidget(self.widget, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(AddUserForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4.setBuddy(self.cardNoField)
        self.label_2.setBuddy(self.nameField)
        self.label_3.setBuddy(self.houseField)

        self.retranslateUi(AddUserForm)
        self.cancelButton.clicked.connect(AddUserForm.close)
        QtCore.QMetaObject.connectSlotsByName(AddUserForm)
        AddUserForm.setTabOrder(self.nameField, self.houseField)
        AddUserForm.setTabOrder(self.houseField, self.cardNoField)
        AddUserForm.setTabOrder(self.cardNoField, self.createButton)
        AddUserForm.setTabOrder(self.createButton, self.cancelButton)

    def retranslateUi(self, AddUserForm):
        _translate = QtCore.QCoreApplication.translate
        AddUserForm.setWindowTitle(_translate("AddUserForm", "Opret ny bruger"))
        self.createButton.setText(_translate("AddUserForm", "&Opret"))
        self.cancelButton.setText(_translate("AddUserForm", "&Annuller"))
        self.label_4.setText(_translate("AddUserForm", "&Kort:"))
        self.label_2.setText(_translate("AddUserForm", "&Navn:"))
        self.label_3.setText(_translate("AddUserForm", "&Hus:"))
        self.label.setText(_translate("AddUserForm", "Opret ny bruger"))

