# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editusers.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditUsersForm(object):
    def setupUi(self, EditUsersForm):
        EditUsersForm.setObjectName("EditUsersForm")
        EditUsersForm.resize(663, 552)
        self.vboxlayout = QtWidgets.QVBoxLayout(EditUsersForm)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(EditUsersForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.widget_3 = QtWidgets.QWidget(EditUsersForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.widget_3)
        self.vboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.vboxlayout1.addWidget(self.label_2)
        self.usersView = QtWidgets.QTableView(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.usersView.setFont(font)
        self.usersView.setSortingEnabled(True)
        self.usersView.setObjectName("usersView")
        self.vboxlayout1.addWidget(self.usersView)
        self.widget = QtWidgets.QWidget(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.widget)
        self.hboxlayout.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.addUserButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.addUserButton.setFont(font)
        self.addUserButton.setObjectName("addUserButton")
        self.hboxlayout.addWidget(self.addUserButton)
        self.deleteUserButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.deleteUserButton.setFont(font)
        self.deleteUserButton.setObjectName("deleteUserButton")
        self.hboxlayout.addWidget(self.deleteUserButton)
        self.zeroUserButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.zeroUserButton.setFont(font)
        self.zeroUserButton.setObjectName("zeroUserButton")
        self.hboxlayout.addWidget(self.zeroUserButton)
        self.vboxlayout1.addWidget(self.widget)
        self.vboxlayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(EditUsersForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout1 = QtWidgets.QHBoxLayout(self.widget_2)
        self.hboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.hboxlayout1.addWidget(self.closeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.vboxlayout.addWidget(self.widget_2)
        self.label_2.setBuddy(self.usersView)

        self.retranslateUi(EditUsersForm)
        QtCore.QMetaObject.connectSlotsByName(EditUsersForm)

    def retranslateUi(self, EditUsersForm):
        _translate = QtCore.QCoreApplication.translate
        EditUsersForm.setWindowTitle(_translate("EditUsersForm", "Ret brugere"))
        self.label.setText(_translate("EditUsersForm", "Ret brugere"))
        self.label_2.setText(_translate("EditUsersForm", "&Brugere:"))
        self.addUserButton.setText(_translate("EditUsersForm", "&Opret ny bruger"))
        self.deleteUserButton.setText(_translate("EditUsersForm", "&Slet bruger"))
        self.zeroUserButton.setText(_translate("EditUsersForm", "&Nulstil valgte brugers saldo"))
        self.closeButton.setText(_translate("EditUsersForm", "&Luk"))

