# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridlayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridlayout.setObjectName("gridlayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.versionLabel.setFont(font)
        self.versionLabel.setTextFormat(QtCore.Qt.PlainText)
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.gridlayout.addWidget(self.versionLabel, 1, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.vboxlayout.setObjectName("vboxlayout")
        self.itemsView = QtWidgets.QTableView(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.itemsView.setFont(font)
        self.itemsView.setAlternatingRowColors(True)
        self.itemsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.itemsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.itemsView.setShowGrid(False)
        self.itemsView.setSortingEnabled(True)
        self.itemsView.setObjectName("itemsView")
        self.vboxlayout.addWidget(self.itemsView)
        self.gridlayout.addWidget(self.groupBox_3, 2, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridlayout1 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridlayout1.setObjectName("gridlayout1")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.gridlayout1.addWidget(self.label_6, 0, 0, 1, 1)
        self.nameField = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameField.setFont(font)
        self.nameField.setTextFormat(QtCore.Qt.PlainText)
        self.nameField.setObjectName("nameField")
        self.gridlayout1.addWidget(self.nameField, 0, 1, 1, 3)
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setObjectName("widget")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.widget)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.vboxlayout1.addWidget(self.label_9)
        self.transactionView = QtWidgets.QTableView(self.widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.transactionView.setFont(font)
        self.transactionView.setAlternatingRowColors(True)
        self.transactionView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.transactionView.setShowGrid(False)
        self.transactionView.setObjectName("transactionView")
        self.vboxlayout1.addWidget(self.transactionView)
        self.gridlayout1.addWidget(self.widget, 0, 4, 8, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.gridlayout1.addWidget(self.label_7, 1, 0, 1, 1)
        self.houseField = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.houseField.setFont(font)
        self.houseField.setText("")
        self.houseField.setObjectName("houseField")
        self.gridlayout1.addWidget(self.houseField, 1, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.gridlayout1.addWidget(self.label_8, 2, 0, 1, 1)
        self.cardnoField = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cardnoField.setFont(font)
        self.cardnoField.setText("")
        self.cardnoField.setObjectName("cardnoField")
        self.gridlayout1.addWidget(self.cardnoField, 2, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.gridlayout1.addWidget(self.label_5, 4, 0, 1, 1)
        self.creditLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.creditLabel.setFont(font)
        self.creditLabel.setTextFormat(QtCore.Qt.PlainText)
        self.creditLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditLabel.setObjectName("creditLabel")
        self.gridlayout1.addWidget(self.creditLabel, 4, 2, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.gridlayout1.addWidget(self.label_10, 5, 0, 1, 2)
        self.totalSpendingLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.totalSpendingLabel.setFont(font)
        self.totalSpendingLabel.setLineWidth(-3)
        self.totalSpendingLabel.setTextFormat(QtCore.Qt.PlainText)
        self.totalSpendingLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalSpendingLabel.setObjectName("totalSpendingLabel")
        self.gridlayout1.addWidget(self.totalSpendingLabel, 5, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.gridlayout1.addWidget(self.label_11, 6, 0, 1, 2)
        self.balanceLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.balanceLabel.setFont(font)
        self.balanceLabel.setTextFormat(QtCore.Qt.PlainText)
        self.balanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.balanceLabel.setObjectName("balanceLabel")
        self.gridlayout1.addWidget(self.balanceLabel, 6, 3, 1, 1)
        self.addMoneyButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.addMoneyButton.setFont(font)
        self.addMoneyButton.setObjectName("addMoneyButton")
        self.gridlayout1.addWidget(self.addMoneyButton, 7, 0, 1, 4)
        self.gridlayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridlayout2.setObjectName("gridlayout2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.gridlayout2.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.gridlayout2.addWidget(self.label_3, 1, 0, 1, 1)
        self.countField = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.countField.setFont(font)
        self.countField.setMinimum(1)
        self.countField.setMaximum(1337)
        self.countField.setObjectName("countField")
        self.gridlayout2.addWidget(self.countField, 1, 1, 1, 1)
        self.orderView = QtWidgets.QTableView(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.orderView.setFont(font)
        self.orderView.setAlternatingRowColors(True)
        self.orderView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.orderView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.orderView.setShowGrid(False)
        self.orderView.setObjectName("orderView")
        self.gridlayout2.addWidget(self.orderView, 1, 3, 4, 1)
        self.removeButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.removeButton.setFont(font)
        self.removeButton.setObjectName("removeButton")
        self.gridlayout2.addWidget(self.removeButton, 2, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.gridlayout2.addWidget(self.addButton, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout2.addItem(spacerItem1, 3, 2, 1, 1)
        self.totalPriceLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.totalPriceLabel.setFont(font)
        self.totalPriceLabel.setTextFormat(QtCore.Qt.PlainText)
        self.totalPriceLabel.setObjectName("totalPriceLabel")
        self.gridlayout2.addWidget(self.totalPriceLabel, 4, 0, 1, 2)
        self.doOrderButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doOrderButton.sizePolicy().hasHeightForWidth())
        self.doOrderButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.doOrderButton.setFont(font)
        self.doOrderButton.setObjectName("doOrderButton")
        self.gridlayout2.addWidget(self.doOrderButton, 5, 0, 1, 2)
        self.gridlayout.addWidget(self.groupBox, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 28))
        self.menubar.setObjectName("menubar")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        self.menu_Hj_lp = QtWidgets.QMenu(self.menubar)
        self.menu_Hj_lp.setObjectName("menu_Hj_lp")
        self.menuFiler = QtWidgets.QMenu(self.menubar)
        self.menuFiler.setObjectName("menuFiler")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionQuit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAddUser = QtWidgets.QAction(MainWindow)
        self.actionAddUser.setObjectName("actionAddUser")
        self.actionEditItems = QtWidgets.QAction(MainWindow)
        self.actionEditItems.setObjectName("actionEditItems")
        self.actionStatistics = QtWidgets.QAction(MainWindow)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionEditUsers = QtWidgets.QAction(MainWindow)
        self.actionEditUsers.setObjectName("actionEditUsers")
        self.actionLoadUser = QtWidgets.QAction(MainWindow)
        self.actionLoadUser.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionLoadUser.setObjectName("actionLoadUser")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAdmin.addAction(self.actionAddUser)
        self.menuAdmin.addAction(self.actionEditUsers)
        self.menuAdmin.addSeparator()
        self.menuAdmin.addAction(self.actionEditItems)
        self.menuAdmin.addSeparator()
        self.menuAdmin.addAction(self.actionStatistics)
        self.menu_Hj_lp.addAction(self.actionAbout)
        self.menuFiler.addAction(self.actionLoadUser)
        self.menuFiler.addSeparator()
        self.menuFiler.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFiler.menuAction())
        self.menubar.addAction(self.menuAdmin.menuAction())
        self.menubar.addAction(self.menu_Hj_lp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.addMoneyButton, self.countField)
        MainWindow.setTabOrder(self.countField, self.removeButton)
        MainWindow.setTabOrder(self.removeButton, self.addButton)
        MainWindow.setTabOrder(self.addButton, self.doOrderButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NatCafé FVK-system v1.1.9"))
        self.label_4.setText(_translate("MainWindow", "NatCafé FVK-system"))
        self.versionLabel.setText(_translate("MainWindow", "Version 1.1.9"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Varer"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kunde-info"))
        self.label_6.setText(_translate("MainWindow", "Navn:"))
        self.nameField.setText(_translate("MainWindow", "Ingen bruger indlæst"))
        self.label_9.setText(_translate("MainWindow", "Tidligere transaktioner:"))
        self.label_7.setText(_translate("MainWindow", "Hus:"))
        self.label_8.setText(_translate("MainWindow", "Kortnr:"))
        self.label_5.setText(_translate("MainWindow", "Kredit:"))
        self.creditLabel.setText(_translate("MainWindow", "Nej"))
        self.label_10.setText(_translate("MainWindow", "Totalt forbrug:"))
        self.totalSpendingLabel.setText(_translate("MainWindow", "0.00 kr"))
        self.label_11.setText(_translate("MainWindow", "Saldo:"))
        self.balanceLabel.setText(_translate("MainWindow", "0.00 kr"))
        self.addMoneyButton.setText(_translate("MainWindow", "&Indsæt penge"))
        self.groupBox.setTitle(_translate("MainWindow", "Foretag ordre"))
        self.label_2.setText(_translate("MainWindow", "Nuværende ordre:"))
        self.label_3.setText(_translate("MainWindow", "Antal:"))
        self.removeButton.setText(_translate("MainWindow", "< &Fjern"))
        self.addButton.setText(_translate("MainWindow", "&Tilføj >"))
        self.totalPriceLabel.setText(_translate("MainWindow", "Total pris: 0000.00 kr."))
        self.doOrderButton.setText(_translate("MainWindow", "&Udfør ordre"))
        self.menuAdmin.setTitle(_translate("MainWindow", "&Admin"))
        self.menu_Hj_lp.setTitle(_translate("MainWindow", "&Hjælp"))
        self.menuFiler.setTitle(_translate("MainWindow", "&Filer"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionQuit.setText(_translate("MainWindow", "&Afslut"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAddUser.setText(_translate("MainWindow", "&Opret ny bruger"))
        self.actionAddUser.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionEditItems.setText(_translate("MainWindow", "Ret &varer"))
        self.actionEditItems.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionStatistics.setText(_translate("MainWindow", "&Statistik"))
        self.actionEditUsers.setText(_translate("MainWindow", "Ret &brugere"))
        self.actionEditUsers.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionLoadUser.setText(_translate("MainWindow", "&Indlæs bruger"))
        self.actionLoadUser.setShortcut(_translate("MainWindow", "F2"))
        self.actionAbout.setText(_translate("MainWindow", "&Om NatCafé FVK"))

