# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistics.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StatisticsForm(object):
    def setupUi(self, StatisticsForm):
        StatisticsForm.setObjectName("StatisticsForm")
        StatisticsForm.resize(836, 634)
        self.vboxlayout = QtWidgets.QVBoxLayout(StatisticsForm)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(StatisticsForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(StatisticsForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridlayout.setObjectName("gridlayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.startTime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.startTime.setCalendarPopup(True)
        self.startTime.setObjectName("startTime")
        self.gridlayout.addWidget(self.startTime, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.endTime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.endTime.setCalendarPopup(True)
        self.endTime.setObjectName("endTime")
        self.gridlayout.addWidget(self.endTime, 0, 6, 1, 1)
        self.sinceStart = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.sinceStart.setFont(font)
        self.sinceStart.setObjectName("sinceStart")
        self.gridlayout.addWidget(self.sinceStart, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.vboxlayout.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(StatisticsForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.vboxlayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(StatisticsForm)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(StatisticsForm)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(StatisticsForm.accept)
        self.buttonBox.rejected.connect(StatisticsForm.reject)
        QtCore.QMetaObject.connectSlotsByName(StatisticsForm)

    def retranslateUi(self, StatisticsForm):
        _translate = QtCore.QCoreApplication.translate
        StatisticsForm.setWindowTitle(_translate("StatisticsForm", "Statistik"))
        self.label.setText(_translate("StatisticsForm", "Statistik"))
        self.groupBox.setTitle(_translate("StatisticsForm", "Periode"))
        self.label_2.setText(_translate("StatisticsForm", "Start:"))
        self.startTime.setDisplayFormat(_translate("StatisticsForm", "yyyy-MM-dd hh:mm"))
        self.label_3.setText(_translate("StatisticsForm", "Slut:"))
        self.endTime.setDisplayFormat(_translate("StatisticsForm", "yyyy-MM-dd hh:mm"))
        self.sinceStart.setText(_translate("StatisticsForm", "Altid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("StatisticsForm", "Tab 1"))

